spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ExpenseTrackerService
    username: sa
    password:

  liquibase:
    change-log: classpath:db/changelog/db1.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

