spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ExpenseTrackerService
    username: sa
    password:
  secondaryDatasource:
    keyspace-name: znaku_keyspace
    contact-points: localhost
    port: 9042
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
#datasource:
#  primaryLiquibase:
#    liquibase:
#      change-log: db.changelog-master.yaml
#  secondaryLiquibase:
#    liquibase:
#      change-log: db2.changelog-master.yaml

logging:
  level:
    org.springframework: INFO
    org.test: DEBUG
    com.liquibase: DEBUG
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
  contexts: development, production

