version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'my-pg-15.3'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=ExpenseTrackerService'
  cassandra:
    image: 'cassandra:latest'
    container_name: 'my-cassandra'
    ports:
      - 9042:9042
    volumes:
      - ./cassandra-data:/var/lib/cassandra/data
